name: Deployment
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION: ${{ secrets.REGION }}
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  ACCOUNT: ${{ secrets.ACCOUNT_ID }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: deploy to dev
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'ActionsPOCStack'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          REGION: $REGION
          AWS_DEFAULT_REGION: $REGION
          ACCOUNT_ID: $ACCOUNT_ID
          ACCOUNT: $ACCOUNT_ID

  deploy-prod:
    runs-on: ububtu-latest
    environment: Prod
    needs: deploy-dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: deploy to prod
        run: echo "deploying to prod"
